мобильная версия главной страницы и страницы компонента
js-tasks-ru/htmlcss-20220317_dasha6 pull request #16
Opened 2022-04-26 17:39 UTC by DariaZherebtsova

2022-04-26 17:40 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-26 17:44 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-04-30 10:05 UTC, GSemikozov requested changes

2022-04-30 10:05 UTC, GSemikozov commented on components/card/card.css
> +    height: 46px;
здесь по высоте не стоит ограничивать, текста может быть и больше. Главное, что этот элемент всегда прижимался к низу карточки

2022-04-30 10:05 UTC, GSemikozov commented on components/footer/footer.css
> +        height: 383px;
не нужно фиксировать высоту

2022-05-01 09:14 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-05-04 19:51 UTC, GSemikozov approved these changes

2022-05-04 19:51 UTC, merged