add solution Toggler task
js-tasks-ru/htmlcss-20220317_dasha6 pull request #19
Opened 2022-05-01 15:04 UTC by DariaZherebtsova

2022-05-01 15:04 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-05-04 19:55 UTC, GSemikozov requested changes

2022-05-04 19:55 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +.toggler__icon rect{
просто .toggler__icon, а fill внутри иконки сделать пустым

2022-05-04 19:55 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +.toggler__icon rect{
и тут

2022-05-04 19:55 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +.toggler__icon rect{
и тут

2022-05-10 13:31 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-05-12 14:26 UTC, GSemikozov approved these changes

2022-05-12 14:26 UTC, merged