lection1 task 02-accordion
js-tasks-ru/htmlcss-20220317_dasha6 pull request #4
Opened 2022-03-26 14:34 UTC by DariaZherebtsova

2022-03-26 14:34 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-03-26 20:11 UTC, GSemikozov requested changes

2022-03-26 20:11 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    width: 730px;
лучше жестко не фиксировать ширину - на мобилке будет плохо

2022-03-26 20:11 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__summary::marker{
есть более надежные способы) 1- часть - в описании задачи, вторая - list-style: none на summary

2022-03-26 20:11 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    width: 730px;
еще не вижу стилей для оформление текста тайтла + скрытого текст (нужно задать класс по БЭМ и соответствующие стили)

2022-03-27 18:53 UTC, DariaZherebtsova commented on 03-lection1/02-accordion/accordion.css
> +    width: 730px;
добавила

2022-03-27 18:54 UTC, DariaZherebtsova commented on 03-lection1/02-accordion/accordion.css
> +.accordion__summary::marker{
поменяла

2022-03-27 18:57 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-03-28 10:24 UTC, GSemikozov approved these changes

2022-03-28 10:24 UTC, merged