lesson2 task1 histogram
js-tasks-ru/htmlcss-20220317_dasha6 pull request #6
Opened 2022-04-02 07:44 UTC by DariaZherebtsova

2022-04-02 07:44 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-02 07:47 UTC, DariaZherebtsova commented on 04-lection2/01-histogram/index.html
> +                    <h4 class="histogram__value">50254</h4>
нужен ли здесь h4, если мы в стилях фиксируем его размер?

2022-04-02 07:48 UTC, DariaZherebtsova commented on 04-lection2/01-histogram/histogram.css
> +    max-width:100px;
не понимаю как flex-basic использовать

2022-04-03 19:00 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +                    <h4 class="histogram__value">50254</h4>
да, с точки зрения СЕО и семантики нужен

2022-04-03 19:01 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    max-width:100px;
flex-basis: 9px

2022-04-03 19:01 UTC, GSemikozov requested changes

2022-04-03 19:01 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    width: 354px;
фиксировать высоту и ширину не надо

2022-04-06 18:57 UTC, GSemikozov approved these changes

2022-04-06 18:57 UTC, merged