lection 3 task 2 Modal
js-tasks-ru/htmlcss-20220317_dasha6 pull request #9
Opened 2022-04-03 15:55 UTC by DariaZherebtsova

2022-04-03 15:56 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-03 19:09 UTC, GSemikozov requested changes

2022-04-03 19:09 UTC, GSemikozov commented on 05-lection3/02-modal/index.html
> +            <div class="modal__background"></div>
удалим

2022-04-03 19:09 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +#modal {
идентификаторы стараемся не использовать, особенно если компоненты 100% будут переиспользоваться (на странице может быть больше 1 модалки)

2022-04-03 19:09 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal__background {
переименовать в .modal, фон задать через rgba, absolute поменять на fixed и поправить хтмл разметку

2022-04-05 19:12 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-06 18:58 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-04-06 19:14 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-04-09 06:53 UTC, DariaZherebtsova commented on assets/css/main.css
> +    --grey-5: #c4c4c479;
Можно так прозрачность задавать или лучше rgba(196, 196, 196, 0.5)?

2022-04-09 07:18 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-04-09 18:47 UTC, GSemikozov commented on assets/css/main.css
> +    --grey-5: #c4c4c479;
лучше более явный вариант с rgba (здесь отдельно выделяется альфа-канал)

2022-04-09 18:48 UTC, GSemikozov requested changes

2022-04-09 18:48 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    position: fixed;
а где display: none делся?)

2022-04-11 14:50 UTC, DariaZherebtsova commented on assets/css/main.css
> +    --grey-5: #c4c4c479;
поменяла на rgba

2022-04-11 14:50 UTC, DariaZherebtsova commented on 05-lection3/02-modal/modal.css
> +    position: fixed;
вернула)

2022-04-12 10:48 UTC, GSemikozov approved these changes

2022-04-12 10:48 UTC, merged